server:
  port: 8083
spring:
  application:
    name: API-GATEWAY
#  configuration of gateway, here lb stands for load balance
  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/**
#          we can give more paths by seperating them with comma
        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotels/**
        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/ratings/**
eureka:
  instance:
    lease-renewal-interval-in-seconds: 30  # Heartbeat every 30 seconds
    lease-expiration-duration-in-seconds: 90
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
