server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userMicroService
    username: root
    password: Mukul@2004
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect